import { Config, VueFontAwesome } from "@ily1606/vue-font-awesome-pro";
import { faCircleExclamation } from "@ily1606/pro-regular-svg-fontawesome";
import {
  faCaretLeft,
  faSpinnerThird,
} from "@ily1606/pro-solid-svg-fontawesome";
import {
  faClouds,
  faLeaf,
  faSunBright,
  faMoon,
  faHouseUser,
  faCloudSunRain,
  faKeyboard,
  faGear,
  faCalendar,
  faSun,
  faLocationArrow,
  faMoonStars,
  faCloudsMoon,
  faCloudMoon,
  faCloud,
  faCloudsSun,
  faCloudFog,
  faCloudDrizzle,
  faCloudSnow,
  faCloudHailMixed,
  faCloudHail,
  faCloudBolt,
  faCloudBoltMoon,
  faSnowBlowing,
  faCloudShowersHeavy,
  faCloudShowers,
  faCloudMoonRain,
  faCloudSleet,
  faRotateRight,
  faPlus,
  faMagnifyingGlass,
  faLocationDot,
  faLocationCheck,
} from "@ily1606/pro-light-svg-fontawesome";
const icons = {
  faCircleExclamation,
  faCaretLeft,
  faClouds,
  faLeaf,
  faSunBright,
  faMoon,
  faHouseUser,
  faCloudSunRain,
  faKeyboard,
  faGear,
  faCalendar,
  faSpinnerThird,
  faSun,
  faLocationArrow,
  faMoonStars,
  faCloudsMoon,
  faCloudMoon,
  faCloud,
  faCloudsSun,
  faCloudFog,
  faCloudDrizzle,
  faCloudSnow,
  faCloudHailMixed,
  faCloudBolt,
  faCloudBoltMoon,
  faSnowBlowing,
  faCloudShowersHeavy,
  faCloudShowers,
  faCloudMoonRain,
  faCloudSleet,
  faCloudHail,
  faRotateRight,
  faPlus,
  faMagnifyingGlass,
  faLocationDot,
  faLocationCheck,
};
const setup = (app) => {
  app.use(Config, icons);
  app.component("VueFontAwesome", VueFontAwesome);
};
export { setup };
